package scopes_service.query_pre_processor.query;

import org.openrdf.model.Value;

/**
 * Created by langens-jonathan on 31.05.16.
 *
 * This is a datastructure representing a triple. It consists of 5 private string
 * objects. All other code is autogenerated with exception of the setObject function
 * that also sets the type and value.
 */
public class Triple
{
    private String subject;
    private String predicate;
    private Value object = null;

    private String objectString = "";
    private String objectType = "";

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        if(subject.startsWith(":"))
        {
            subject = subject.substring(1, subject.length());
        }
        this.subject = subject;
    }

    public Value getObject() {
        return object;
    }

    public void setObject(Value object) {
        this.object = object;
        this.objectString = object.stringValue();
        if(this.objectString.startsWith(":"))
        {
            this.objectString = this.objectString.substring(1, this.objectString.length());
        }
        this.objectType = object.toString().substring(0, this.objectString.length());
    }

    public void setObject(String fullObject)
    {
        if(fullObject.indexOf("^^") > -1)
        {
            int index = fullObject.indexOf("^^");
            this.setObjectString(fullObject.substring(0, index));
            this.setObjectType(fullObject.substring(index + 2, fullObject.length()));
        }
        else
        {
            this.setObjectString(fullObject);
        }
    }

    public String getPredicate() {
        return predicate;
    }

    public void setPredicate(String predicate) {
        if(predicate.startsWith(":"))
        {
            predicate = predicate.substring(1, predicate.length());
        }
        this.predicate = predicate;
    }

    public void setObjectString(String objectString){
        if(objectString.startsWith(":"))
        {
            objectString = objectString.substring(1, objectString.length());
        }
        this.objectString = objectString;
    }

    public String getObjectAsString()
    {
        String toreturn = this.objectString;
        if(toreturn.endsWith("\"") || toreturn.startsWith("\""))
        {
            if(!toreturn.endsWith("\""))
                toreturn += "\"";
            if(!toreturn.startsWith("\""))
                toreturn = "\"" + toreturn;
            return toreturn;
        }
        if(!toreturn.startsWith("<"))
            toreturn = "<" + toreturn;
        if(!toreturn.endsWith(">"))
            toreturn += ">";
        return toreturn;
    }

    public String getObjectString() {return this.objectString;}

    public void setObjectType(String objectType) { this.objectType = objectType;}

    public String getObjectType() {
        return this.objectType;}
}
